### ISSUE TITLE
Can you help me configure NavPi on a different system other than the Raspberry Pi?

### ISSUE THREAD

**Issue by rfgamaral** [Encrypt-S/navpi#19]
Hello,

I'm trying to setup this project on a different system than the Raspberry Pi and although I've mode some progress I still don't have the UI 100% working. So far I've setup a multi-container Docker application running an HTTP server (NGINX), a PHP app (this one) and the NAV Coin Core linux daemon. The server and PHP are working and the UI can successfully communicate with the daemon.

But this is what I get when I access the PHP app:

![image](https://user-images.githubusercontent.com/96476/32984471-1fbff634-cc9f-11e7-8f0b-9310c8551d6c.png)

This `primaryNavcoinaddress.php` file doesn't exist anywhere in this repository. I've noticed that `setprimary.php` creates this file but who is responsible to create the first version of this file? Am I missing an "install" step on this Nav Pi setup?

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-25T06:44:09+13:00","ped":"2017-11-25T08:59:59+13:00"})

**Comment by stabastian** [comment]
Check the permission of files.I made an image of the navpi enviroment, it needs an refactoring because it is the same image for the apache and of the navcoind service, I want to split in two images and running with docker-compose.

Check my image: https://github.com/sebaponti/docker-navcoind

**Comment by rfgamaral** [comment]
> Check the permission of files.

I don't understand what permissions has to do with the warning message above... The app is trying to include a file that does not exist in the repository, how fixing permissions will fix that problem?

But which files are you referring too?

> I made an image of the navpi enviroment, it needs an refactoring because it is the same image for the apache and of the navcoind service, I want to split in two images and running with docker-compose.

I'm trying to do the same but I writing everything from scratch because I'm taking this opportunity to also learn Docker. I'm taking this step-by-step so I can understand every little detail of both Docker and Nav Pi.

**Comment by rfgamaral** [comment]
Hey @craigmacgregor, can you give me an hint here?

**Comment by rfgamaral** [comment]
😭
